# Use VS Code extension "REST Client" to run this file

@baseUrl = http://localhost:8080

# Login user
# @name login
POST {{baseUrl}}/users/login
Content-Type: application/json

{
  "username": "johndoe5",
  "password": "secret"
}

@accessToken = {{login.response.body.access_token}}
@refreshToken = {{login.response.body.refresh_token}}

###

# Renew token
POST {{baseUrl}}/tokens/renew-access-token
Content-Type: application/json

{
  "refresh_token": "{{refreshToken}}"
}

###

# Create user
POST {{baseUrl}}/users
Content-Type: application/json

{
  "username": "johndoe5",
  "full_name": "John Doe Five",
  "email": "john.doe5@email.com",
  "password": "secret"
}

###

# Create account
POST {{baseUrl}}/accounts
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "owner": "johndoe5",
    "currency": "USD"
}

###

# Get one account
GET {{baseUrl}}/accounts/133
Authorization: Bearer {{accessToken}}

###

# Get all accounts with pagination
GET {{baseUrl}}/accounts?page_id=1&page_size=10
Authorization: Bearer {{accessToken}}

### 

# Create Transfer
POST {{baseUrl}}/transfers
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "from_account_id": 3,
  "to_account_id": 5,
  "amount": 100,
  "currency": "USD"
}

### 
