# Use VS Code extension "REST Client" to run this file

@baseUrl = http://localhost:8080

# Login user
# @name login
POST {{baseUrl}}/users/login
Content-Type: application/json

{
  "username": "johndoe5",
  "password": "secret"
}

@authToken = {{login.response.body.access_token}}

###

# Create user
POST {{baseUrl}}/users
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "username": "johndoe5",
  "full_name": "John Doe 5",
  "email": "john.doe5@email.com",
  "password": "secret"
}

###

# Create account
POST {{baseUrl}}/accounts
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "owner": "johndoe5",
    "currency": "USD"
}

###

# Get one account
GET {{baseUrl}}/accounts/133
Authorization: Bearer {{authToken}}

###

# Get all accounts with pagination
GET {{baseUrl}}/accounts?page_id=1&page_size=10
Authorization: Bearer {{authToken}}

### 

# Create Transfer
POST {{baseUrl}}/transfers
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "from_account_id": 3,
  "to_account_id": 5,
  "amount": 100,
  "currency": "USD"
}

### 
