# Use VS Code extension "REST Client" to run this file

@baseUrl = http://localhost:8080

# Login user (gRPC Gateway)
# @name login
POST {{baseUrl}}/v1/login_user
Content-Type: application/json

{
  "username": "johndoe5",
  "password": "secret"
}

@accessToken = {{login.response.body.access_token}}
@refreshToken = {{login.response.body.refresh_token}}

###

# Create user (gRPC Gateway)
POST {{baseUrl}}/v1/create_user
Content-Type: application/json

{
  "username": "johndoe2",
  "full_name": "John Doe",
  "email": "john.doe2@email.com",
  "password": "secret"
}


###

# Update user (gRPC Gateway)
PATCH {{baseUrl}}/v1/update_user
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "username": "johndoe5",
  "full_name": "New John Doe Five",
  "email": "john.doe5@email.com",
  "password": "secret"
}

###
