name: Deploy to Amazon ECR

on:
  push:
    branches: [ "main" ]

jobs:

  deploy:
    permissions:
      id-token: write
      contents: read

    name: Build image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install kubeclt
      uses: azure/setup-kubectl@v4
      with:
        version: 'v1.30.3' # default is latest stable
      id: install-kubectl

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Load secrets and save to app.env
      run: aws secretsmanager get-secret-value --secret-id simple_bank --query SecretString --output text | jq -r 'to_entries | map("\(.key)=\(.value)")|.[]' > app.env

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: simplebank
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -t $REGISTRY/$REPOSITORY:latest .
        docker push -a $REGISTRY/$REPOSITORY

    - name: Update Kubernetes configuration
      run: aws eks update-kubeconfig --name simple-bank --region us-east-1

    # - name: Deploy image to Amazon EKS
    #   run: |
    #     kubectl apply -f eks/aws-auth.yaml
    #     kubectl apply -f eks/deployment.yaml
    #     kubectl apply -f eks/service.yaml
    #     kubectl apply -f eks/issuer.yaml
    #     kubectl apply -f eks/ingress.yaml

